# Generated by Django 5.2.6 on 2026-02-12 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_post',
            name='subject',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='resources_post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
