# Generated by Django 5.2.6 on 2026-02-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
