# Generated by Django 5.2.6 on 2026-02-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_resources_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_post',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
