# Generated by Django 5.2.6 on 2026-02-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_pics/sparks_profile.png', upload_to='profile_pics/'),
        ),
    ]
