# Generated by Django 5.2.6 on 2026-03-05 16:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resources_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_post',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
