# Generated by Django 5.2.6 on 2026-03-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_resources_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_post',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
